# HBASE TABLE
TABLE_BINANCE = 'BINANCE'
TABLE_INFO = 'INFO'

# HBASE SCHEMA
SCHEMA_BINANCE_TABLE = {"CANDLESTICKS": dict(), "TECHNICAL_INDICATORS": dict()}
BINANCE_TABLE_COLUMNS = ['CANDLESTICKS:close', 'CANDLESTICKS:close_time', 'CANDLESTICKS:high',
                         'CANDLESTICKS:low', 'CANDLESTICKS:open', 'CANDLESTICKS:volume']
SCHEMA_INFO_TABLE = {"MARKET_DATA": dict()}
