name: ci
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run linter (Ruff)
        run: ruff check src/ tests/

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run typechecker (Mypy)
        run: mypy src/opa/

  test:
    needs:
      - lint
      - typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Cache talib_compilation
        id: cache-talib
        uses: actions/cache@v5
        with:
          path: |
            /usr/lib/libta_lib* 
            /usr/include/ta-lib
          key: ${{ runner.os }}-talib

      - name: Install TA-LIB
        if: steps.cache-talib.outputs.cache-hit != 'true'
        run: sh install_talib.sh

      - name: Install dependencies
        run: pip install -e '.[dev]'

      - name: Run test
        run: pytest --cov --cov-report=term-missing

  build-docker:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build api image
        run: docker build . -f docker/api/Dockerfile -t ghcr.io/${{ github.repository_owner }}/api:${{ github.sha }} && docker push ghcr.io/${{ github.repository_owner }}/api:${{ github.sha }}

      - name: Build collect_hd image
        run: docker build . -f docker/collectors/historic/Dockerfile  -t ghcr.io/${{ github.repository_owner }}/collect_hd:${{ github.sha }} && docker push ghcr.io/${{ github.repository_owner }}/collect_hd:${{ github.sha }}

      - name: Build collect_sd image
        run: docker build . -f docker/collectors/stream/Dockerfile -t ghcr.io/${{ github.repository_owner }}/collect_sd:${{ github.sha }} && docker push ghcr.io/${{ github.repository_owner }}/collect_sd:${{ github.sha }}

      - name: Build stream2hbase image
        run: docker build . -f docker/pipeline/hbase/Dockerfile -t ghcr.io/${{ github.repository_owner }}/stream2hbase:${{ github.sha }} && docker push ghcr.io/${{ github.repository_owner }}/stream2hbase:${{ github.sha }}
